console.log('Dit is het begin van de log.')
console.log(document.getElementById('main').innerHTML)
console.log(document.getElementById('title').innerHTML)
console.log(document.getElementById('content').innerHTML)
console.log('Dit is het einde van de log.')